CREATE TABLE log
(
	
	id				int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	chave				VARCHAR		NOT NULL,
	texto			VARCHAR		not null,
	datalog			DATE,
	codigoretorno		INTEGER		NOT NULL,
	retorno			INTEGER		NULL	

)
